gText_WouldYouLikeToRestYourPkmn::
	.string "Welcome to the POKéMON CENTER.\n"
	.string "Would you like to rest your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "Hello, {PLAYER}! You want the usual?$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"
